name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install
        run: pip install .
      - name: Install development requirements
        run: pip install -r services/flaskapp/requirements.txt
      - name: Test
        run: pytest
